### ISSUE TITLE
Do not see hyperlinks to my videos in S3 per the search results, no video snippet.

### ISSUE THREAD

**Issue by rajeev2509** [aws-samples/mediasearch-with-amazon-q-transcribe#7]
Hi Team, 
﻿This is one of the best solutions I came across. Thank you so much for your efforts.
﻿I ran into an issue. I do not see hyperlinks to my videos in S3 per the search results, as shown in the attachment. By that, I can not run any video from the middle per the search result. also 'Sources' section show only direct video links, no video snippet. 
﻿Please assist.
<img width="576" alt="issue" src="https://github.com/user-attachments/assets/9ff6ef2b-638b-4f11-90b1-9d7c6fe7a673">
<img width="576" alt="issue2" src="https://github.com/user-attachments/assets/913e457b-08c0-49eb-9c4b-a1d536e713f5">

**Comment by roshansthomas** [comment]
Hey @rajeev2509 Thanks for your feedback. 
You are currently using the Web application that is deployed as part AMazon Q BUsiness application. If you check the Finder cloudformation stack, you will notice a output paramter **MediaSearchFinderURL**. 

i.e. follow instructions in section **Deploy the Mediasearch Q Business finder component**

Do let me know how you go.

At the moment, the solution plays the video on s3 from the first time stamp where the first relevant occurence occurs. PLaying from multiple stamps is a great feature request. At the moment though, the solution does not do that. i.e. play the video from the middle.

**Comment by roshansthomas** [comment]
Working as designed. Please use the MS Finder application which is a react JS app. The URL for the app is the value of the cloudformation parameter **MediaSearchFinderURL**.
